[world]
name = "Cairo Arena"
seed = "dev"

[world.socials]
x = "https://x.com/WarpackMasters"
discord = "https://discord.gg/tjJJHc7JtP"
github = "https://github.com/ImpulseDAO/Cairo_Arena"
telegram = ""

[namespace]
default = "arena"

[env]
rpc_url = ""
# Default account for katana with seed = 0
account_address = ""
private_key = ""

[writers]
"arena" = ["arena-actions", "arena-fight_system"]