[package]
cairo-version = "=2.7.0"
name = "cairo_arena"
version = "0.2.160"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-rc.1" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.0-rc.1" }

[[target.starknet-contract]]